version: '3'

services:
  test-task-api:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - test-task-postgres
    links:
      - test-task-postgres
    volumes:
      - ./:/home/node/app
    command: npm run start:dev

  test-task-postgres:
    image: postgres:11
    restart: always

    ports:
      - 3001:5432

    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
