version: '3'

services:
  mixit-api:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - mixit-postgres
      - mixit-redis
      - mixit-minio
    links:
      - mixit-postgres
      - mixit-redis
      - mixit-minio
    volumes:
      - ./:/home/node/app
    command: npm run start:dev

  mixit-postgres:
    image: postgres:11
    restart: always

    ports:
      - 3001:5432

    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
